FROM ubuntu:latest as build
RUN apt-get update
RUS apt-get install openjdk-20-jdk -y
COPY . .
RUN ./mvnw bootJar --no-daemon

FROM openjdk:20-jdk-slim
ESPOSE 8080
COPY --from-build /build/libs/telkomedika-api-1.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
